### ISSUE TITLE
Can you update this so that it works with Laravel Mix 6?

### ISSUE THREAD

**Issue by t0byman** [michtio/laravel-mix-criticalcss#12]
See title.

**Comment by terryupton** [comment]
Do you have plans to support Mix 6 @michtio? I know you've moved to native webpack now. But would be super if this still worked with the new v6.

**Comment by michtio** [comment]
Later this month I'll have some time to revise some older things @terryupton I'll put this one on the list as well :)

**Comment by michtio** [comment]
Later this month I'll have some time to revise some older things @terryupton I'll put this one on the list as well :)

**Comment by terryupton** [comment]
Thanks @michtio after using it i believe it works ok with Mix 6. But it might benefit from the latest critical. Thank you. 👍🏻😎

**Comment by CreateSean** [comment]
Has this been updated to work with Laravel 6?

**Comment by michtio** [comment]
It should work with Laravel Mix 6 @CreateSean 
Only thing on my list is to update to Critical 2.0

**Comment by CreateSean** [comment]
Sorry, I did get it working and I forgot to update this thread. 

I'm good now.

**Comment by jstnmthw** [comment]
Tried installing with Laravel Mix 6 and npm complaining it cannot resolve dependencies.
`npm ERR! Could not resolve dependency:
npm ERR! peer laravel-mix@"^4.0.0" from laravel-mix-criticalcss@1.0.1`

If it works with Mix v6 then maybe want to update **package.json**
`
"peerDependencies": {
    "laravel-mix": "^4.0.0"
}
`

**Comment by michtio** [comment]
good shout @jstnmthw 

Will update this in the coming week and add it to my task list.

For my own reference: `^4.0.0 || ^5.0.0 || ^6.0.0` should work

**Comment by ademers** [comment]
I'm still unable to get this working with Mix 6.
I can't seem to get rid of the peer dependency issue and am also getting error `[webpack-cli] TypeError: Cannot read property 'content-type' of undefined` which appears to be cause by not using Critical 2.0. See https://github.com/addyosmani/critical/issues/414#issuecomment-693711287

**Comment by ryanmasuga** [comment]
We tried getting this working with Laravel Mix 6 today and weren't able to get it installed. 
```
npm ERR! Could not resolve dependency:
npm ERR! peer laravel-mix@"^4.0.0" from laravel-mix-criticalcss@1.0.1
```

**Comment by asha23** [comment]
Can confirm this still isn't working.

`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: brightlocal@1.0.0
npm ERR! Found: laravel-mix@6.0.25
npm ERR! node_modules/laravel-mix
npm ERR!   dev laravel-mix@"^6.0.0-beta.17" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer laravel-mix@"^4.0.0" from laravel-mix-criticalcss@1.0.1
npm ERR! node_modules/laravel-mix-criticalcss
npm ERR!   laravel-mix-criticalcss@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

**Comment by asha23** [comment]
Having an issue installing with Mix 6

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: ********@1.0.0
npm ERR! Found: laravel-mix@6.0.25
npm ERR! node_modules/laravel-mix
npm ERR!   dev laravel-mix@"^6.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer laravel-mix@"^4.0.0" from laravel-mix-criticalcss@1.0.1
npm ERR! node_modules/laravel-mix-criticalcss
npm ERR!   laravel-mix-criticalcss@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
```

**Comment by michtio** [comment]
I have updated the peer dependencies to `^4.0.0 || ^5.0.0 || ^6.0.0` 

Could you give it a spin? and let me know if it is installable @asha23 @ryanmasuga @ademers

**Comment by jamesdoc** [comment]
I had these errors when installing via `npm`, however adding `"laravel-mix-criticalcss": "michtio/laravel-mix-criticalcss#1.0.2"` to `package.json` installed fine.

**Comment by michtio** [comment]
@jamesdoc that's interesting to see, since it should actually just installed the 1.0.2 version. 
Maybe it makes sense to remove the package-lock and rerun npm install.

**Comment by eboye** [comment]
I'm facing the same problem:

```
❯ npm install laravel-mix-criticalcss --save-dev
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: laravel-mix@6.0.25
npm ERR! node_modules/laravel-mix
npm ERR!   dev laravel-mix@"^6.0.19" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer laravel-mix@"^4.0.0" from laravel-mix-criticalcss@1.0.1
npm ERR! node_modules/laravel-mix-criticalcss
npm ERR!   dev laravel-mix-criticalcss@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by scottwakefield** [comment]
Hi @michtio,

It doesn't look like npm has picked up the latest `1.0.2` release yet (https://www.npmjs.com/package/laravel-mix-criticalcss), so it's not possible to install via npm.

As @jamesdoc mentioned, you can get it to work by referencing the release directly from your `package.json` file, but it would be nice to not have to do that.

Would it be possible to publish the new `1.0.2` release to npm? 🤞

**Comment by htuzel** [comment]
I  tried to install it via package.json but still doesn't work.  It seems it needs a new build or sth. similar.

**Comment by michtio** [comment]
@scottwakefield @htuzel @jamesdoc 

I'll try to rerelease today or tomorrow. It's strange it's not picked up.

As an update, it's republished. Sorry for the delay. Tried to publish it on the wrong account 🤦🏻

**Comment by mylesthedev** [comment]
👀
