### ISSUE TITLE
after using laravel-mix-critical how to remove critical from the main CSS?

### ISSUE THREAD

**Issue by nekooee** [michtio/laravel-mix-criticalcss#14]
after using laravel-mix-critical how to remove critical from the main CSS?
I used the X package. A CSS file of critical classes is now created. But all of these classes are also present in the main CSS and have not been deleted. This means that these classes are now loaded twice. How to remove them from the main CSS?

my close :
```javascript
mix.js('resources/js/admin.js', 'public/js')
    .js('resources/js/app.js', 'public/js')
    .js('resources/js/front.js', 'public/js').vue()
    .postCss('resources/css/admin.css', 'public/css')
    .postCss('resources/css/vue-treeselect.css', 'public/css')
    .postCss('resources/css/defer.css', 'public/css')
    .postCss('resources/css/app.css', 'public/css', [
        require('tailwindcss'),
    ])
    .polyfill({
        enabled: true,
        useBuiltIns: "usage",
        targets: "last 2 versions, not ie <= 10",
    })
    .criticalCss({
        enabled: mix.inProduction(),
        paths: {
            base: 'http://dev-app.com/',
            templates: './public/css/',
            suffix: '_critical.min'
        },
        urls: [
            { url: '/', template: 'app' },
        ],
        options: {
            minify: true,
        },
    })
    .webpackConfig(require('./webpack.config'))

if (mix.inProduction()) {
    mix.version()
        .sourceMaps()
        .webpackConfig({devtool: 'source-map'});
}

```

**Comment by michtio** [comment]
@nekooee that is intended behaviour, it is not because critical css classes are being generated these classes need to be deleted from the main.css file. 

Imagine the classes in your main.css being reused on another page in the footer, and on another in the above the fold part. If it would be removed from `main.css` the footer on any other page would never be styled anymore.

**Comment by nekooee** [comment]
> 

thank you. But on my site, due to the low size of the critical classes, I added the critical classes of the whole site in the header. It is only necessary to enter the critical classes of each page separately when the site is very heavy and large.
This means that on my site it is not necessary for critical classes to be in the main.css file.
Is there no way to remove duplicate classes in WebPack?
