### ISSUE TITLE
Css file not generated from the styles of the page

### ISSUE THREAD

**Issue by vm-web** [michtio/laravel-mix-criticalcss#7]
Hi,
I'm working on a not Laravel project, to be precise a WordPress theme.

This is my webpack.mix.js code:

```let mix = require('laravel-mix');

require('laravel-mix-criticalcss');
mix
    .sass('src/app.scss', 'dist')
    .criticalCss({
        enabled: mix.inProduction(),
        paths: {
            base: 'http://website.local',
            templates: './dist/css-critical/'
        },
        urls: [
            { url: '/', template: 'home' },
        ],
        options: {
            minify: true,
        },
    });
```
After running the `npm run prod` command, sass task works correctly.
But criticalCss task seems simply getting the app.css and exporting on css-critical directory.

I'm not sure if I'm right: I think script should extract the critical css from the css included in the page, indipendently from the sass task. Am I right?

Thank you for the help

**Comment by michtio** [comment]
Can you refine your question @vm-web ? 
If you feed only `app.scss` then Critical will watch ( according to the options ) on the viewport height you've set, and read the classes from what will be displayed from above the fold, it will then extract those styles/classes from your `app.scss` file and create a critical css file which you can include in your template ( with include you still need to inline the code from that css file generated )

**Comment by michtio** [comment]
Issue closed as to no response
