### ISSUE TITLE
Allow flexible filename pattern

### ISSUE THREAD

**Issue by elgandoz** [michtio/laravel-mix-criticalcss#8]
In some scenario, we may want to allow to a more flexible filename pattern.
Currently the pattern is fixed to `TEMPLATE_critical.min.css`.

I'm using laravel-mix in conjunction with Drupal, and the system is expecting a different structure for critical css' (`./critical/PATH.css`). 

Although it may be an edge case, I think it would be very useful for different setups having this sort of flexibility. 

By default, we can maintain the current pattern.

**Comment by michtio** [comment]
Pull Request has been merged in
